name: Log Forwarder

on:
  workflow_run:
    workflows: ['Build and Deploy']
    types: [completed]

jobs:
  forward-logs:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    
    steps:
    - name: Dump GitHub Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    
    - name: Forward Logs to Custom API
      env:
        LOG_WEBHOOK_URL: ${{ secrets.TESTLOG }}
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{\"workflow_name\":\"${{ github.workflow }}\",\"commit_sha\":\"${{ github.sha }}\",\"job_name\":\"${{ github.job }}\",\"error_message\":\"${{ fromJson(steps.dump-github-context.outputs.GITHUB_CONTEXT).event.workflow_run.conclusion }}\"}" "$LOG_WEBHOOK_URL"