name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: yarn install
    - name: Build
      id: build
      run: |
        OUTPUT=$(yarn build 2>&1)
        echo "::set-output name=build_output::$OUTPUT"
        yarn build

    - name: Send log on build failure
      if: ${{ failure() }}
      env:
        LOG_WEBHOOK_URL: ${{ secrets.TESTLOG }}
      run: |
        BUILD_LOG=$(echo '${{ steps.build.outputs.build_output }}' | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
        ERROR_MESSAGE=$(echo "$BUILD_LOG" | grep -A2 "Failed to compile." | tr '\n' ' ')
        curl --insecure -X POST -H "Content-Type: application/json" -d "{\"workflow_name\":\"${{ github.workflow }}\",\"commit_sha\":\"${{ github.sha }}\",\"job_name\":\"${{ github.job }}\",\"error_message\":\"$ERROR_MESSAGE\",\"build_log\":\"$BUILD_LOG\"}" "$LOG_WEBHOOK_URL"
    
    - name: main
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TESTAUTO }}
        publish_dir: ./build
